### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by Mohammed-Musab-Khan** [attreyabhatt/KivyMD-Basics#3]
I'm getting ReferenceError while running this code

Main.py

from kivymd.app import MDApp
from kivy.lang import Builder
from kivy.core.window import Window

navigation_helper = """
Screen:
	NavigationLayout:
		ScreenManager:
			Screen:
				BoxLayout:
					orientation:'vertical'
					MDToolbar:
						title:'Demo Appication'
						left_action_items : [ [ "menu", lambda x: nav_drawer.toggle_nav_drawer() ]  ]
						elevation:10
					Widget:
		MDNavigationDrawer:
			id:nav_drawer
"""

class DemoApp( MDApp):
	def build( self ):
		self.theme_cls.primary_palette = 'Red'
		screen = Builder.load_string( navigation_helper )
		return screen
		
					
DemoApp().run()

Output:

[INFO   ] [Logger      ] Record log in /storage/emulated/0/Books/Python/Games/KivyMD/.kivy/logs/kivy_20-09-29_10.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.3 (default, May 27 2020, 02:08:17) 
[GCC 9.3.0]
[INFO   ] [Python      ] Interpreter at "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3"
[INFO   ] [KivyMD      ] v0.104.1
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 V@331.0 (GIT@cf57c9c, I1cb5c4d1cc) (Date:09/23/18)'>
[INFO   ] [GL          ] OpenGL vendor <b'Qualcomm'>
[INFO   ] [GL          ] OpenGL renderer <b'Adreno (TM) 509'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 2
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [GL          ] NPOT texture support is available
[WARNING] [Base        ] Unknown <android> provider
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/storage/emulated/0/Books/Python/Games/KivyMD/Navigation Drawer.py", line 28, in <module>
     DemoApp().run()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/kivy/app.py", line 855, in run
     runTouchApp()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/kivy/base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/kivy/core/window/window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/kivy/core/window/window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/kivy/base.py", line 339, in idle
     Clock.tick()
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/kivy/clock.py", line 591, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 154, in kivy._clock.ClockEvent.tick
   File "kivy/_clock.pyx", line 86, in kivy._clock.ClockEvent.get_callback
   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/kivy/weakmethod.py", line 56, in is_dead
     return self.proxy is not None and not bool(dir(self.proxy))
 ReferenceError: weakly-referenced object no longer exists

**Comment by jay-stance** [comment]
ME TOO..
And it's quite annoying after following up all your videos
